services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: date-knight-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: date_knight
      MYSQL_USER: dk_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dk_mysql_data:/var/lib/mysql

volumes:
  dk_mysql_data:
